---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install dependencies
  apt:  pkg={{item}} state=present
  with_items:
    - linux-headers-generic

- name: Download network installer
  get_url:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
    dest: /root/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
    checksum: md5:4b8004dd747dbb664e85b17dec3fee51

- name: Install apt cuda repo (deb)
  apt:
    deb: /root/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb

- name: Add apt key(s)
  apt_key: url="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub"

- name: Install cuda packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - cuda

- name: Setup cuda symlink to cuda 9.0 path
  file: src=/usr/local/cuda-9.0 dest=/usr/local/cuda
        state=link

- stat: path=/home/{{ administrator_user }}/.bashrc_custom
  register: p

- name: Create extended bashrc if necessary
  file: path=/home/{{ administrator_user }}/.bashrc_custom
        owner={{ administrator_user }}
        group={{ administrator_user }}
        mode=0770
        state={{ "file" if  p.stat.exists else "touch"}}

- name: Add cuda to path (.bashrc_custom)
  lineinfile:
    path: /home/{{ administrator_user }}/.bashrc_custom
    line: 'export PATH=/usr/local/cuda/bin:${PATH}'

- name: Add cuda to ld library path (.bashrc_custom)
  lineinfile:
    path: /home/{{ administrator_user }}/.bashrc_custom
    line: 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}'
